import { Noto_Sans_Georgian } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'

const notoSansGeorgian = Noto_Sans_Georgian(
  {
    subsets: ['georgian', 'latin', 'latin-ext']
  }
)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSansGeorgian.className}>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
